name: Template
options:
  bundleIdPrefix: com.Template
  xcodeVersion: '12.4'
  deploymentTarget: '13.0'
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: true
  minimumXcodeGenVersion: '2.18.0'
  
  configs:
  Debug.Dev: debug
  Debug.Prod: debug
  Release: release

targets:
  Template:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    settings:
      base:
        MARKETING_VERSION: 1.0
    sources:
       - path: ./Sources
    
